### ISSUE TITLE
Merge AddServer and UpdateServer

### ISSUE THREAD

**Issue by JesusLuvsYooh** [SoftwareGuy/NodeListServer#6]
Merge AddServer and UpdateServer - 
Extra function in Unity currently needed, to do similar thing at the NLS side.
And this way, if the game list gets closed for whatever reason, games will auto add themselves next Coroutine/call.
At moment they cannot, as they cannot re-add (update) if add is not called first.

**Comment by SoftwareGuy** [comment]
Closing as it's done
